version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=fodicat
      - DB_PASSWORD=secret
      - DB_NAME=mydb
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: mariadb:11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=fodicat
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
